/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;



import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author keviu
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    User cliente =new User();
    User auxiliar =new User();
    Secuencial objSecuencial = new Secuencial();
    FileMethods archivos = new FileMethods();
    Mensaje Publicacion = new Mensaje();
    String fotografía;
    String descripción = "Añade una breve descripción";
    String RutaU = "c:\\MEIA\\Usuarios.txt";
    String RutaBU = "c:\\MEIA\\BitácoraUsuarios.txt";
    String DescriptorU = "c:\\MEIA\\DescriptorU.txt";
    String DescriptorBU = "c:\\MEIA\\DescriptorBU.txt";
    String RutaA = "c:\\MEIA\\Lista_Amigos.txt";
    String RutaBA = "c:\\MEIA\\BitácoraAmigos.txt";
    String DescriptorA = "c:\\MEIA\\DescriptorA.txt";
    String DescriptorBA = "c:\\MEIA\\DescriptorBA.txt";
    String RutaG = "c:\\MEIA\\Grupos.txt";
    String RutaBG = "c:\\MEIA\\BitácoraGrupos.txt";
    String DescriptorG = "c:\\MEIA\\DescriptorG.txt";
    String DescriptorBG = "c:\\MEIA\\DescriptorBG.txt";
    String RutaM = "c:\\MEIA\\Mensajes.txt";
    String RutaBM =  "c:\\MEIA\\BitácoraMensajes.txt";
    String DescriptorM = "c:\\MEIA\\DescriptorM.txt";
    String DescriptorBM = "c:\\MEIA\\DescriptorBM.txt";
    String [] ArregloDeImagenes;
    int  count = 1;
    public Administracion() {
        initComponents();
             
    }
    public Administracion(User uncliente) {
        initComponents();
        cliente=uncliente  ; 
        if (cliente.getRol().equals("0")) {
//            TabMantemiento.setEnabledAt(TabMantemiento.indexOfComponent(jPanel1),false);
            TabMantemiento.removeTabAt(TabMantemiento.indexOfComponent(jPanel2));
            TabMantemiento.removeTabAt(TabMantemiento.indexOfComponent(jPanel3));
            jButton1.setVisible(true);
        }
        else{
            Registro n=new Registro();
            JInternalFrame internalFrame = new JInternalFrame();
            n.OcultarCerrar(true);
            internalFrame.setContentPane(n.getContentPane());
            internalFrame.pack();
            internalFrame.setVisible(true);
            this.Escritorio.add(internalFrame);
            BtnDarBAja.setVisible(false);
        }
        BtnGuardarAd.setVisible(false);
        BtnDarBajaAd.setVisible(false);
        jLabel2.setText(cliente.getUser());
        String[] nacimiento=cliente.getDate().split(Pattern.quote("/"));
        cbDía.setSelectedItem(nacimiento[0]);
        cbMes.setSelectedItem(nacimiento[1]);
        cbAño.setSelectedItem(nacimiento[2]);
        tfNCorreo.setText(cliente.getEmail());
        tfNTeléfono.setText(Integer.toString(cliente.getCelNumber()));
        TADescriptor.setText(cliente.getDescription());
        L_usuarioActual.setText(cliente.getUser());
        
        ImageIcon imagen = new ImageIcon(cliente.getPhotoPath());
        FotoPerfil.setIcon(imagen);
        //modificamos la imagen
        ImageIcon icon = new ImageIcon(cliente.getPhotoPath());
        Image img = icon.getImage();
        //cambiamos el tamaño de la imagen
        Image newimg = img.getScaledInstance(178,167, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);
        FotoPerfil.setIcon(newIcon);
        FotoPerfil.setSize(178,167);
       
//        LfotoPerfil;
        
        
        
     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LfotoPerfil = new javax.swing.JLabel();
        TabOpciones = new javax.swing.JTabbedPane();
        PMantenimiento = new javax.swing.JPanel();
        TabMantemiento = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        TfBusquedaAd = new javax.swing.JTextField();
        BtnBuscarAd = new javax.swing.JButton();
        BtnDarBajaAd = new javax.swing.JButton();
        BtnGuardarAd = new javax.swing.JButton();
        lbNContraseña1 = new javax.swing.JLabel();
        tfNContraseña1 = new javax.swing.JPasswordField();
        lbNContraseñaNueva1 = new javax.swing.JLabel();
        tfNContraseñaNueva1 = new javax.swing.JPasswordField();
        lbCumpleaños1 = new javax.swing.JLabel();
        cbDía1 = new javax.swing.JComboBox<>();
        cbMes1 = new javax.swing.JComboBox<>();
        cbAño1 = new javax.swing.JComboBox<>();
        tfNCorreo1 = new javax.swing.JTextField();
        lbCorreo1 = new javax.swing.JLabel();
        lbTeléfono1 = new javax.swing.JLabel();
        tfNTeléfono1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TADescriptor1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        cbMes = new javax.swing.JComboBox<>();
        cbAño = new javax.swing.JComboBox<>();
        tfNCorreo = new javax.swing.JTextField();
        tfNTeléfono = new javax.swing.JTextField();
        tfNContraseñaNueva = new javax.swing.JPasswordField();
        lbNContraseña = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbTeléfono = new javax.swing.JLabel();
        cbDía = new javax.swing.JComboBox<>();
        btnImagen = new javax.swing.JButton();
        LModificarDatos = new javax.swing.JLabel();
        lbNContraseñaNueva = new javax.swing.JLabel();
        tfNContraseña = new javax.swing.JPasswordField();
        lbCumpleaños = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TADescriptor = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        PBusqueda = new javax.swing.JPanel();
        BtnBuscar = new javax.swing.JButton();
        TfBusquedaNoAd = new javax.swing.JTextField();
        LBusqueNoAd = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Solocitudes = new javax.swing.JPanel();
        FrameSolicitudes = new javax.swing.JInternalFrame();
        BtnSolicitud = new javax.swing.JButton();
        BtnVerAmigos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbMAmigos2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMActualizar = new javax.swing.JButton();
        cbMAmigos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfNMensaje = new javax.swing.JTextArea();
        cbTipo = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfPublico = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tfPrivado = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfMEmisor = new javax.swing.JTextField();
        tfMReceptor = new javax.swing.JTextField();
        tfMFecha = new javax.swing.JTextField();
        btnMEliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        List_amigosI = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        L_foto = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        L_exito = new javax.swing.JLabel();
        BtnDarBAja = new javax.swing.JButton();
        BrnCerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        L_usuarioActual = new javax.swing.JLabel();
        FotoPerfil = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabOpcionesMouseClicked(evt);
            }
        });

        Escritorio.setPreferredSize(new java.awt.Dimension(483, 325));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        TabMantemiento.addTab("Nuevo Usuario", jPanel2);

        BtnBuscarAd.setText("Buscar");
        BtnBuscarAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarAdActionPerformed(evt);
            }
        });

        BtnDarBajaAd.setText("Dar de Baja");
        BtnDarBajaAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDarBajaAdActionPerformed(evt);
            }
        });

        BtnGuardarAd.setText("Guardar Datos");
        BtnGuardarAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarAdActionPerformed(evt);
            }
        });

        lbNContraseña1.setText("Contraseña");

        lbNContraseñaNueva1.setText("Nueva Contraseña");

        lbCumpleaños1.setText("Fecha Nacimiento");

        cbDía1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic" }));

        cbAño1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        lbCorreo1.setText("Correo");

        lbTeléfono1.setText("Teléfono");

        tfNTeléfono1.setMinimumSize(new java.awt.Dimension(10, 20));

        jLabel4.setText("Descripcion");

        TADescriptor1.setColumns(20);
        TADescriptor1.setRows(5);
        jScrollPane3.setViewportView(TADescriptor1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNContraseña1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCorreo1)
                                    .addComponent(lbCumpleaños1)
                                    .addComponent(lbTeléfono1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNCorreo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNTeléfono1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbNContraseñaNueva1)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbDía1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbAño1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfNContraseña1)
                                    .addComponent(tfNContraseñaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnDarBajaAd)
                            .addComponent(BtnGuardarAd))
                        .addContainerGap(367, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TfBusquedaAd, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscarAd))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscarAd)
                    .addComponent(TfBusquedaAd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtnDarBajaAd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(BtnGuardarAd))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNContraseña1)
                            .addComponent(tfNContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNContraseñaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNContraseñaNueva1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCumpleaños1)
                            .addComponent(cbDía1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCorreo1)
                            .addComponent(tfNCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNTeléfono1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbTeléfono1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        TabMantemiento.addTab("Busqueda Administrativa", jPanel3);

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic" }));

        cbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        tfNTeléfono.setMinimumSize(new java.awt.Dimension(10, 20));

        lbNContraseña.setText("Contraseña");

        lbCorreo.setText("Correo");

        lbTeléfono.setText("Teléfono");

        cbDía.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        btnImagen.setText("Nueva Foto de Perfil");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        LModificarDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LModificarDatos.setText("Modificar Datos");

        lbNContraseñaNueva.setText("Nueva Contraseña");

        lbCumpleaños.setText("Fecha Nacimiento");

        BtnGuardar.setText("Guardar Datos");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        TADescriptor.setColumns(20);
        TADescriptor.setRows(5);
        jScrollPane2.setViewportView(TADescriptor);

        jLabel3.setText("Descripcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnImagen)
                .addGap(105, 105, 105)
                .addComponent(BtnGuardar)
                .addGap(0, 490, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNContraseña)
                    .addComponent(lbNContraseñaNueva)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCorreo)
                            .addComponent(lbCumpleaños)
                            .addComponent(lbTeléfono, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDía, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfNContraseña)
                                    .addComponent(tfNContraseñaNueva)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNTeléfono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(LModificarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LModificarDatos)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNContraseña)
                    .addComponent(tfNContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNContraseñaNueva)
                    .addComponent(tfNContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCumpleaños)
                    .addComponent(cbDía, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCorreo)
                    .addComponent(tfNCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNTeléfono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbTeléfono, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagen)
                    .addComponent(BtnGuardar))
                .addGap(19, 19, 19))
        );

        TabMantemiento.addTab("Usuario", jPanel1);

        javax.swing.GroupLayout PMantenimientoLayout = new javax.swing.GroupLayout(PMantenimiento);
        PMantenimiento.setLayout(PMantenimientoLayout);
        PMantenimientoLayout.setHorizontalGroup(
            PMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabMantemiento)
        );
        PMantenimientoLayout.setVerticalGroup(
            PMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMantenimientoLayout.createSequentialGroup()
                .addComponent(TabMantemiento, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabOpciones.addTab("Mantenimiento", PMantenimiento);

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        LBusqueNoAd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2108, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PBusquedaLayout = new javax.swing.GroupLayout(PBusqueda);
        PBusqueda.setLayout(PBusquedaLayout);
        PBusquedaLayout.setHorizontalGroup(
            PBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBusquedaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PBusquedaLayout.createSequentialGroup()
                        .addComponent(TfBusquedaNoAd, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscar))
                    .addGroup(PBusquedaLayout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBusqueNoAd, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PBusquedaLayout.setVerticalGroup(
            PBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar)
                    .addComponent(TfBusquedaNoAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PBusquedaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LBusqueNoAd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBusquedaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        TabOpciones.addTab("Busqueda", PBusqueda);

        Solocitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLicpanel(evt);
            }
        });

        FrameSolicitudes.setVisible(true);

        javax.swing.GroupLayout FrameSolicitudesLayout = new javax.swing.GroupLayout(FrameSolicitudes.getContentPane());
        FrameSolicitudes.getContentPane().setLayout(FrameSolicitudesLayout);
        FrameSolicitudesLayout.setHorizontalGroup(
            FrameSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        FrameSolicitudesLayout.setVerticalGroup(
            FrameSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2150, Short.MAX_VALUE)
        );

        BtnSolicitud.setText("Solicitudes");
        BtnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSolicitudActionPerformed(evt);
            }
        });

        BtnVerAmigos.setText("Amigos");
        BtnVerAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerAmigosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SolocitudesLayout = new javax.swing.GroupLayout(Solocitudes);
        Solocitudes.setLayout(SolocitudesLayout);
        SolocitudesLayout.setHorizontalGroup(
            SolocitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolocitudesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(FrameSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(SolocitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnVerAmigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        SolocitudesLayout.setVerticalGroup(
            SolocitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolocitudesLayout.createSequentialGroup()
                .addGroup(SolocitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolocitudesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(BtnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BtnVerAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SolocitudesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FrameSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabOpciones.addTab("Solicitudes", Solocitudes);

        jLabel5.setFont(new java.awt.Font("Broadway", 3, 14)); // NOI18N
        jLabel5.setText("MENSAJES PUBLICOS:");

        jLabel6.setFont(new java.awt.Font("Broadway", 3, 14)); // NOI18N
        jLabel6.setText("MENSAJES PRIVADOS:");

        jLabel7.setFont(new java.awt.Font("Broadway", 3, 14)); // NOI18N
        jLabel7.setText("ESCRIBIR MENSAJE:");

        jLabel2.setText("Para:");

        btnMActualizar.setText("Actualizar Mensajes");
        btnMActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActualizarActionPerformed(evt);
            }
        });

        tfNMensaje.setColumns(20);
        tfNMensaje.setRows(5);
        jScrollPane1.setViewportView(tfNMensaje);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Público", "Privado" }));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        tfPublico.setColumns(20);
        tfPublico.setRows(5);
        jScrollPane5.setViewportView(tfPublico);

        jLabel8.setFont(new java.awt.Font("Broadway", 3, 14)); // NOI18N
        jLabel8.setText("ELIMINAR MENSAJE:");

        tfPrivado.setColumns(20);
        tfPrivado.setRows(5);
        jScrollPane6.setViewportView(tfPrivado);

        jLabel9.setText("Emisor:");

        jLabel10.setText("Receptor:");

        jLabel11.setText("Fecha & Hora");

        btnMEliminar.setText("Eliminar");
        btnMEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEliminarActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar Amigos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMAmigos2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbMAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnviar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfMEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(tfMReceptor)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMEliminar)
                                    .addComponent(tfMFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)
                    .addComponent(jLabel9)
                    .addComponent(tfMEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfMReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfMFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMEliminar)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnMActualizar)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMAmigos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        TabOpciones.addTab("Mensajes", jPanel4);

        jPanel5.setEnabled(false);

        jLabel12.setText("Mis amigos");

        List_amigosI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_amigosIMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(List_amigosI);

        jButton4.setText("Subir una imagen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(530, 530, 530)
                                .addComponent(L_exito))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(226, 226, 226))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(17, 17, 17)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(L_exito)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(L_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        TabOpciones.addTab("Imágenes", jPanel5);

        BtnDarBAja.setText("Dar de Baja");
        BtnDarBAja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDarBAjaActionPerformed(evt);
            }
        });

        BrnCerrar.setText("Cerrar Sesion");
        BrnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrnCerrarActionPerformed(evt);
            }
        });

        jButton1.setText("Backup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGrupos.setText("Grupos");
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });

        jButton2.setText("Reorganizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Enviar mensaje a grupos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LfotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BtnDarBAja)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 71, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FotoPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addGap(63, 63, 63))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BrnCerrar)
                                        .addGap(88, 88, 88))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(L_usuarioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(LfotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(L_usuarioActual)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDarBAja, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(BrnCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(TabOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        FileMethods metodos= new FileMethods();
        String busqueda = objSecuencial.busqueda(false, TfBusquedaNoAd.getText(), RutaBU, RutaU);
        String[]nume=busqueda.split(Pattern.quote("|")) ;
        String nulo="";
        Secuencial listaA =new Secuencial(RutaU);
        busqueda=listaA.busqueda(true, TfBusquedaNoAd.getText(), RutaBU, RutaU);
        if(nume[0].equals(nulo))
        {
            LBusqueNoAd.setText("El usuario "+TfBusquedaNoAd.getText()+" no existe");
            
        }
        else{
            LBusqueNoAd.setText("El usuario "+TfBusquedaNoAd.getText()+" si existe");
            
            
//             JOptionPane.showMessageDialog(null,"EL Usuario: "+LBusqueNoAd.getText()+" No esxiste", "Usuario o contraseña incorrecta", WIDTH);
        }
        JButtonTableExample frame = new JButtonTableExample(busqueda,1,cliente);
        jInternalFrame1.setContentPane(frame.getContentPane());
        
        
       
        
       
//        jPanel4.addComponent(frame);

//       Tabla t=new Tabla();
//       t.seeTable(TablaBusquedaU, BtnBuscar);
//        


    }//GEN-LAST:event_BtnBuscarActionPerformed

    
    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed

        //Seleccionar una foto de perfil.
        fotografía = archivos.fotoPerfil(this);
    }//GEN-LAST:event_btnImagenActionPerformed

    private void BrnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BrnCerrarActionPerformed
//BOTóN: dar de baja
    private void BtnDarBAjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDarBAjaActionPerformed
        // TODO add your handling code here:
         FileMethods metodos= new FileMethods();
        try {
            Secuencial SecuencialSalida = new Secuencial();
            String[] Data = SecuencialSalida.busqueda(true, cliente.getUser(), RutaBA, RutaA).split(Pattern.quote("|"));
            if(!Data[0].equals(""))
            {
                for (int i = 0; i < Data.length; i++) {
                    String[] atributos = Data[i].split(Pattern.quote(","));
                    SecuencialSalida.Eliminar(SecuencialSalida.busqueda(false, atributos[0]+"|"+atributos[1], RutaBA, RutaA));
                }
            }
            String emergencia = cliente.getUser();
            SecuencialSalida.Eliminar(SecuencialSalida.busqueda(false, cliente.getUser(), RutaBU, RutaU));
            this.dispose();
            SecuencialSalida.ActualizarDescriptor(DescriptorBU, emergencia);
            SecuencialSalida.ActualizarDescriptor(DescriptorU, emergencia);
            SecuencialSalida.ActualizarDescriptor(DescriptorBA, emergencia);
            SecuencialSalida.ActualizarDescriptor(DescriptorA, emergencia);
             // Jackie-9/10/2017
//        String busqueda=metodos.busqueda(cliente.getRegistro());
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }

        

        
        
    }//GEN-LAST:event_BtnDarBAjaActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        //Verificar Contraseña
        String contraseñaEncriptada;
        String contraseñaEncriptadavieja = archivos.EncriptadoMD5(tfNContraseña.getText());
        
        if((!tfNContraseñaNueva.getText().equals(""))&cliente.getPassword().equals(contraseñaEncriptadavieja)){
            contraseñaEncriptada = archivos.EncriptadoMD5(tfNContraseñaNueva.getText());
            cliente.setPassword(contraseñaEncriptada);
        }
        cliente.setDate(cbDía.getSelectedItem()+"/"+cbMes.getSelectedItem()+"/"+cbAño.getSelectedItem());
        cliente.setEmail(tfNCorreo.getText());
        cliente.setCelNumber(Integer.parseInt(tfNTeléfono.getText()));
        cliente.setDescription(TADescriptor.getText());
        FileMethods metodos= new FileMethods();
        try {
            String busqueda = objSecuencial.busqueda(false,cliente.getUser(), RutaBU, RutaU);
            objSecuencial.Actualizar(busqueda,cliente.getRegistro());
            JOptionPane.showMessageDialog(null,"Datos Modificado", "Modificacion", WIDTH);
//        String busqueda=metodos.busqueda(cliente.getRegistro());
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnBuscarAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarAdActionPerformed
        // TODO add your handling code here:
        FileMethods metodos= new FileMethods();
        String busqueda = objSecuencial.busqueda(false, TfBusquedaAd.getText(), RutaBU, RutaU);
        String[]nume=busqueda.split(Pattern.quote("|")) ;
        String nulo="";
        if(nume[0].equals(nulo))
        {
            JOptionPane.showMessageDialog(null,"El usuario "+TfBusquedaAd.getText()+" si existe", "Modificacion", WIDTH);
        }
        else{
        auxiliar = objSecuencial.readUser(busqueda);
        BtnGuardarAd.setVisible(true);
        BtnDarBajaAd.setVisible(true);
        String[] nacimiento=auxiliar.getDate().split(Pattern.quote("/"));
        cbDía1.setSelectedItem(nacimiento[0]);
        cbMes1.setSelectedItem(nacimiento[1]);
        cbAño1.setSelectedItem(nacimiento[2]);
        tfNCorreo1.setText(auxiliar.getEmail());
        tfNTeléfono1.setText(Integer.toString(auxiliar.getCelNumber()));
        TADescriptor1.setText(auxiliar.getDescription());
        
//             JOptionPane.showMessageDialog(null,"EL Usuario: "+LBusqueNoAd.getText()+" No esxiste", "Usuario o contraseña incorrecta", WIDTH);
        }
    }//GEN-LAST:event_BtnBuscarAdActionPerformed
//BOTóN: daar de baja
    private void BtnDarBajaAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDarBajaAdActionPerformed
        // TODO add your handling code here:
        FileMethods metodos= new FileMethods();
        try {
            String busqueda = objSecuencial.busqueda(false, auxiliar.getUser(), RutaBU, RutaU);
            objSecuencial.Eliminar(busqueda);
            objSecuencial.ActualizarDescriptor(DescriptorU, "");
            this.dispose();
            objSecuencial.ActualizarDescriptor(DescriptorBU, "");
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnDarBajaAdActionPerformed

    private void BtnGuardarAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarAdActionPerformed
        // TODO add your handling code here:
        auxiliar.setDate(cbDía1.getSelectedItem()+"/"+cbMes1.getSelectedItem()+"/"+cbAño1.getSelectedItem());
        auxiliar.setEmail(tfNCorreo1.getText());
        auxiliar.setCelNumber(Integer.parseInt(tfNTeléfono1.getText()));
        auxiliar.setDescription(TADescriptor1.getText());
        FileMethods metodos= new FileMethods();
        try {
            String busqueda= objSecuencial.busqueda(false, auxiliar.getUser(), RutaBU, RutaU);
            objSecuencial.Actualizar(busqueda, auxiliar.getRegistro());
            JOptionPane.showMessageDialog(null,"Datos Modificado", "Modificacion", WIDTH);
//        String busqueda=metodos.busqueda(cliente.getRegistro());
        } catch (IOException ex) {
            Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGuardarAdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Backup b=new Backup();
        b.setUser(cliente);
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CLicpanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLicpanel
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CLicpanel

    private void BtnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSolicitudActionPerformed
        // TODO add your handling code here:
        FileMethods metodos= new FileMethods();
        String busqueda=objSecuencial.busqueda(false, TfBusquedaNoAd.getText(), RutaBU, RutaU);
        String[]nume=busqueda.split(Pattern.quote("|")) ;
        String nulo="";
        Secuencial listaA =new Secuencial(RutaBA);
        busqueda=listaA.busqueda(true, cliente.getUser(), RutaBA, RutaA);
        
        JButtonTableExample frame = new JButtonTableExample(busqueda,2,cliente);
        FrameSolicitudes.setContentPane(frame.getContentPane());
    }//GEN-LAST:event_BtnSolicitudActionPerformed

    private void BtnVerAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerAmigosActionPerformed
        // TODO add your handling code here:
        FileMethods metodos= new FileMethods();
        String busqueda=objSecuencial.busqueda(false, TfBusquedaNoAd.getText(), RutaBU, RutaU);
        String[]nume=busqueda.split(Pattern.quote("|")) ;
        String nulo="";
        Secuencial listaA =new Secuencial(RutaBA);
        busqueda=listaA.busqueda(true, cliente.getUser(), RutaBA, RutaA);
        
        JButtonTableExample frame = new JButtonTableExample(busqueda,3,cliente);
        FrameSolicitudes.setContentPane(frame.getContentPane());
    }//GEN-LAST:event_BtnVerAmigosActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        // Llamar al formulario de mantenimiento de grupos
        MantenimientoGrupos Frame  = new MantenimientoGrupos();
        Frame.SetMantenimientoGrupos(cliente);
        Frame.setVisible(true);
    }//GEN-LAST:event_btnGruposActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Secuencial objetoSecuencial = new Secuencial();
        objetoSecuencial.reorganizar(3, RutaU, RutaBU);        
        objetoSecuencial.ActualizarDescriptor(DescriptorU, "");
        File A = new File(RutaBA);
        if(A.exists())
        {
            objetoSecuencial.reorganizar(3, RutaA, RutaBA);
            objetoSecuencial.ActualizarDescriptor(DescriptorA, "");
            archivos.createFile(RutaBA);
        }
        File G = new File(RutaBG);
        if(G.exists())
        {
            objetoSecuencial.reorganizar(3, RutaG, RutaBG);
            objetoSecuencial.ActualizarDescriptor(DescriptorG, "");
            archivos.createFile(RutaBG);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        if(!tfNMensaje.getText().equals(""))
        {
            Publicacion.setEmisor(cliente.getUser());
            Publicacion.setReceptor(cbMAmigos.getSelectedItem().toString());
            Publicacion.setFecha((new Date()).toString());
            Publicacion.setMensaje(tfNMensaje.getText());
            if(cbTipo.getSelectedItem() == "Público")
            {
                Publicacion.setTipo(0);
            }
            else
            {
                Publicacion.setTipo(1);
            }
            objSecuencial.Insertar(RutaBM, new User(), new Solicitud(), new Grupo(), Publicacion);
        }
        tfNMensaje.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnMActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActualizarActionPerformed
        //Limpiar los textarea (publico y privado)
        tfPublico.setText("");
        tfPrivado.setText("");
        // Actualizar combobox de amigos y los mensajes públicos.
        //Obtener la lista de amigos del usuario.
        String concatenados = cliente.ObtenerAmigos();
        if(!concatenados.equals("")) //Si tengo amigos
        {
            String[] Amigos = concatenados.split(Pattern.quote(","));
            for (int i = 0; i < Amigos.length; i++) {
                //Por cada amigo obtengo sus mensajes publicos y los escribo.
                concatenados = objSecuencial.busqueda(true, Amigos[i], RutaBM, RutaM);
                if(!concatenados.equals("|0"))
                {
                    String[] Mensajes = concatenados.split(Pattern.quote("|"));
                    for (int j = 0; j < Mensajes.length; j++) {
                        String[] DatosMensaje = Mensajes[j].split(Pattern.quote(","));
                        if(DatosMensaje[3].equals("0")) // si es un mensaje publico
                        {
                            tfPublico.append(DatosMensaje[0]+"->"+DatosMensaje[1]+" "+DatosMensaje[2]+"\r\n"+DatosMensaje[4]+"\r\n");
                        }
                        //Escribir los mensajes privados del usuario seleccionado.
                        if(Amigos[i].equals(cbMAmigos2.getSelectedItem()))
                        {
                            //(Si el emisor es el usuario o el amigo seleccionado) y (el receptor es el usuario o el amigo seleccionado) y el mensaje es privado
                            if((DatosMensaje[0].equals(cliente.getUser()) || DatosMensaje[0].equals(Amigos[i])) & (DatosMensaje[1].equals(cliente.getUser()) || DatosMensaje[1].equals(Amigos[i])) & DatosMensaje[3].equals("1") )
                            {
                                tfPrivado.append(DatosMensaje[0]+"->"+DatosMensaje[1]+" "+DatosMensaje[2]+"\r\n"+DatosMensaje[4]+"\r\n");
                            }
                        }
                    }
                }
            }
            //Mensaje de grupos
            tfPrivado.append("\r\n" + "------Mensaje de grupos------"+ "\r\n" );
            String todosLosMensajes = objSecuencial.busqueda(true, cliente.getUser(), RutaBM, RutaM); //del usuario loggeado
            String [] prueba  = todosLosMensajes.split(Pattern.quote("|"));
            for (int i = 0; i < prueba.length; i++) {
                String[] partesDelMensaje = prueba[i].split(Pattern.quote(","));
                //buscar como emisor
               // tfPrivado.append("Mensajes enviados:"+ "\r\n" );
                String buscar = objSecuencial.busqueda(false, prueba[i].split(Pattern.quote(","))[0], objSecuencial.RutaBA, objSecuencial.RutaA);
                if (buscar.equals("|0")) {
                    tfPrivado.append("("+partesDelMensaje[2] + ")" +partesDelMensaje[0]+" para "+partesDelMensaje[1]+" :"+partesDelMensaje[4]+"\r\n");
                }             
                
            }
            /*for (int i = 0; i < prueba.length; i++) {
                String[] partesDelMensaje = prueba[i].split(Pattern.quote(","));
                //buscar como receptor
                tfPrivado.append("Mensajes recibidos:"+ "\r\n" );
                String buscar = objSecuencial.busqueda(false, prueba[i].split(Pattern.quote(","))[1], objSecuencial.RutaBA, objSecuencial.RutaA);
                if (buscar.equals("|0")) {
                    tfPrivado.append("("+partesDelMensaje[2] + ")" +partesDelMensaje[0]+" para "+partesDelMensaje[1]+" :"+partesDelMensaje[4]+"\r\n");
                }             
                
            }*/
           
        } 
        
    }//GEN-LAST:event_btnMActualizarActionPerformed

    private void btnMEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEliminarActionPerformed
        // Eliminar el mensaje especificado. 1. Filltros
        if(!tfMEmisor.getText().equals("") & !tfMReceptor.getText().equals("") & !tfMFecha.getText().equals("") )
        {
            String busqueda = objSecuencial.busqueda(false, tfMEmisor.getText()+"|"+tfMReceptor.getText()+"|"+tfMFecha.getText(), RutaBM, RutaM);
            if(!busqueda.equals("|0")) //2. Si se encuentra el mensaje eliminarlo
            {
                try {
                    objSecuencial.Eliminar(busqueda);
                } catch (IOException ex) {
                    Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //3. Devolver los textfield a sus valores por defecto.
            tfMEmisor.setText("");
            tfMReceptor.setText("");
            tfMFecha.setText("");
        }
    }//GEN-LAST:event_btnMEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //Obtener la lista de amigos del usuario.
        String concatenados = cliente.ObtenerAmigos();
        if(!concatenados.equals("")) //Si tengo amigos
        {
            String[] Amigos = concatenados.split(Pattern.quote(","));
            //A partir de eso construir los combobox
            try
            {
                if(cbMAmigos.getComponentCount() != 0)
                {
                    cbMAmigos.removeAllItems();
                    cbMAmigos2.removeAllItems();
                }
            }catch(Exception e){}
            for (int i = 0; i < Amigos.length; i++) {
                cbMAmigos.addItem(Amigos[i]);
                cbMAmigos2.addItem(Amigos[i]);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SubirImagenes jfrom = new SubirImagenes();
        jfrom.Usuario(cliente);
        jfrom.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TabOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabOpcionesMouseClicked
        // TODO add your handling code here:
        DefaultListModel modeloAmigos = new DefaultListModel();
        jLabel14.setText(cliente.getUser());
        String resultado = objSecuencial.busqueda(false, cliente.getUser(), objSecuencial.RutaBU, objSecuencial.RutaU);
        
        if (resultado !="|0") {
            User objUser = objSecuencial.readUser(resultado);
            
            String[] amigosUsuario = objUser.ObtenerAmigos().split(",");
            if(amigosUsuario[0]!=""){
                for (int i = 0; i < amigosUsuario.length; i++) 
                    modeloAmigos.addElement(amigosUsuario[i]);
            }else{
                
                modeloAmigos.addElement("No tienes amigos en tu lista de amigos");
                L_exito.setText("No hay imágenes que mostrar");
               
            }    
                            
        }
        pruebaImagen("C:\\Users\\jsala\\Documents\\RedSocial\\ProyectoArchivos-Kevin-Yo\\ProyectoArchivos\\build\\classes\\galeria.png",506,259);
        List_amigosI.setModel(modeloAmigos);
        
    }//GEN-LAST:event_TabOpcionesMouseClicked

    private void BuscarImagen(String unUsuario){
        
    }
    //KEVIN ACA AGREGAS EL METODO BUSCAR DEL ARBOL PARA QUE TE RETORNE TODAS LAS RUTAS
    private void List_amigosIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_amigosIMouseClicked
        // TODO add your handling code here:
        
        String seleccionado = List_amigosI.getSelectedValue().toString();
        if (seleccionado != "No tienes amigos en tu lista de amigos") {
            //ArregloDeImagenes = BuscarImagen(seleccionado); //este metodo es del arbol binario y debe regresar  todas las fotos de un usuario, le mando el nombre del usuario
            count = 1;
            
                ArbolBB arbol=new ArbolBB();
            String [] prueba = null;
            try {
                prueba=arbol.busquedaInterna(seleccionado).split(Pattern.quote("|"));
            } catch (IOException ex) {
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
            //esta es la linea que modificas, lo demás queda igual
            // = {"C:\\Users\\jsala\\Pictures\\WhatsApp Image 2016-10-24 at 11.53.18 PM.jpeg", "C:\\Users\\jsala\\Pictures\\Saved Pictures\\WhatsApp Image 2016-11-19 at 1.59.38 PM.jpeg"}; //arreglo de las imágenes
            ArregloDeImagenes = prueba;
            pruebaImagen(ArregloDeImagenes[0],506,259);
        }
                
        
    }//GEN-LAST:event_List_amigosIMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(ArregloDeImagenes.length==0){
            
        }
        else{
            if (count < ArregloDeImagenes.length) {
            pruebaImagen(ArregloDeImagenes[count],506,259);
            count++;
            }
            else{
                count = 0;
                pruebaImagen(ArregloDeImagenes[count],506,259);
                count++;
            }
        }
            
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EnviarMensajes jfrom = new EnviarMensajes();
        jfrom.Usuario(cliente);
        jfrom.setVisible(true);
       
    }//GEN-LAST:event_jButton6ActionPerformed

    public void pruebaImagen(String fotografias, int x, int y)	{
        ImageIcon imagen = new ImageIcon(fotografias);
        L_foto.setIcon(imagen);
        //modificamos la imagen
        ImageIcon icon = new ImageIcon(fotografias);
        Image img = icon.getImage();
        //cambiamos el tamaño de la imagen
        Image newimg = img.getScaledInstance(x,y, java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);
        L_foto.setIcon(newIcon);
        L_foto.setSize(x,y);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
                
                
            }
           
        });
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrnCerrar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscarAd;
    private javax.swing.JButton BtnDarBAja;
    private javax.swing.JButton BtnDarBajaAd;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnGuardarAd;
    private javax.swing.JButton BtnSolicitud;
    private javax.swing.JButton BtnVerAmigos;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel FotoPerfil;
    private javax.swing.JInternalFrame FrameSolicitudes;
    private javax.swing.JLabel LBusqueNoAd;
    private javax.swing.JLabel LModificarDatos;
    private javax.swing.JLabel L_exito;
    private javax.swing.JLabel L_foto;
    private javax.swing.JLabel L_usuarioActual;
    private javax.swing.JLabel LfotoPerfil;
    private javax.swing.JList<String> List_amigosI;
    private javax.swing.JPanel PBusqueda;
    private javax.swing.JPanel PMantenimiento;
    private javax.swing.JPanel Solocitudes;
    private javax.swing.JTextArea TADescriptor;
    private javax.swing.JTextArea TADescriptor1;
    private javax.swing.JTabbedPane TabMantemiento;
    private javax.swing.JTabbedPane TabOpciones;
    private javax.swing.JTextField TfBusquedaAd;
    private javax.swing.JTextField TfBusquedaNoAd;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnMActualizar;
    private javax.swing.JButton btnMEliminar;
    private javax.swing.JComboBox<String> cbAño;
    private javax.swing.JComboBox<String> cbAño1;
    private javax.swing.JComboBox<String> cbDía;
    private javax.swing.JComboBox<String> cbDía1;
    private javax.swing.JComboBox<String> cbMAmigos;
    private javax.swing.JComboBox<String> cbMAmigos2;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbMes1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbCorreo1;
    private javax.swing.JLabel lbCumpleaños;
    private javax.swing.JLabel lbCumpleaños1;
    private javax.swing.JLabel lbNContraseña;
    private javax.swing.JLabel lbNContraseña1;
    private javax.swing.JLabel lbNContraseñaNueva;
    private javax.swing.JLabel lbNContraseñaNueva1;
    private javax.swing.JLabel lbTeléfono;
    private javax.swing.JLabel lbTeléfono1;
    private javax.swing.JTextField tfMEmisor;
    private javax.swing.JTextField tfMFecha;
    private javax.swing.JTextField tfMReceptor;
    private javax.swing.JPasswordField tfNContraseña;
    private javax.swing.JPasswordField tfNContraseña1;
    private javax.swing.JPasswordField tfNContraseñaNueva;
    private javax.swing.JPasswordField tfNContraseñaNueva1;
    private javax.swing.JTextField tfNCorreo;
    private javax.swing.JTextField tfNCorreo1;
    private javax.swing.JTextArea tfNMensaje;
    private javax.swing.JTextField tfNTeléfono;
    private javax.swing.JTextField tfNTeléfono1;
    private javax.swing.JTextArea tfPrivado;
    private javax.swing.JTextArea tfPublico;
    // End of variables declaration//GEN-END:variables
}
