/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;

/**
 *
 * @author jsala
 */
public class GrupoAmigos extends javax.swing.JFrame {

    /**
     * Creates new form GrupoAmigos
     */
 
    User usuario;
    DefaultListModel amigos = new DefaultListModel();
    DefaultListModel integrantes = new DefaultListModel();
    DefaultListModel grupos = new DefaultListModel();
    //Secuencial secuencial = new Secuencial();
    SecuencialIndizado secuencialIndizado = new SecuencialIndizado();
    Secuencial secuencial = new Secuencial("");
    String amigoSeleccionado = "";
    String grupoSeleccionado;
    Grupo objGrupo;
    int numeroDeIntegrantes;
    String[] amigosDelUsuario;
   
    public GrupoAmigos() {
        initComponents();
        
    }
    public void SetGrupoAmigos(DefaultListModel grupos, User usuario){
        this.grupos = grupos;
        this.usuario = usuario;
        MostrarGrupos();
        this.tfUsario.setText(usuario.getUser());
        
        numeroDeIntegrantes = 0;        
        
    }
    private void AmigosDelUsuario(){
        amigosDelUsuario = secuencial.busqueda(true, usuario.getUser(), secuencial.RutaBA, secuencial.RutaA).split(Pattern.quote("|"));
        for (int i = 0; i < amigosDelUsuario.length; i++) {
            String[] temp = amigosDelUsuario[i].split(Pattern.quote(","));
            if (temp[2] != "0") {
                if (usuario.getUser().equals(temp[0])) {
                    amigos.add(i, temp[1]);
                }
                if (usuario.getUser().equals(temp[1])) {
                    amigos.add(i, temp[0]);
                }
            }
            
        }
        listAmigos.setModel(amigos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listAmigos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listIntegrantes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbGrupoActual = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfUsario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNumeroIntegrantes = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAmigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listAmigos);

        jScrollPane2.setViewportView(listIntegrantes);

        jLabel1.setText("Tus amigos");

        jLabel2.setText("Integrantes");

        jLabel3.setText("Grupo Actual");

        cbGrupoActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbGrupoActualMouseClicked(evt);
            }
        });
        cbGrupoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrupoActualActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuario:");

        tfUsario.setEnabled(false);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Añadir amigo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Integrantes:");

        tfNumeroIntegrantes.setEnabled(false);

        jButton4.setText("j");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButton1))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbGrupoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUsario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNumeroIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUsario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbGrupoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfNumeroIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)))
                .addGap(9, 9, 9)
                .addComponent(jButton3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
//añadir amigo
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // AñadirIntegrante();
        if ((amigoSeleccionado != "" || amigoSeleccionado !=null) && (grupoSeleccionado != null || grupoSeleccionado != "")) {
            grupoSeleccionado = cbGrupoActual.getSelectedItem().toString();
             secuencialIndizado.EscribirIndizado(SecuencialIndizado.GRUPOAMIGOS, FormatoDeData(usuario.getUser(),grupoSeleccionado, amigoSeleccionado));
             AñadirIntegrante();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private String FormatoDeData(String usuario, String grupo, String usuarioAmigo){
        Date fecha = new Date();
        return Rellenar(usuario,30,"#") +  Rellenar(grupo, 30, "#")  + Rellenar(usuarioAmigo,20,"#")  + fecha + "|" + 1;
    }
    private String Rellenar(String var,int cantidad,String relleno) {
        String registro = "";
        registro+=var;
        for (int i = var.length(); i < cantidad; i++) {
           registro+=relleno; 
        }
        return registro+="|"; 
    }
    private void listAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAmigosMouseClicked
        // TODO add your handling code here:
        amigoSeleccionado = listAmigos.getSelectedValue().toString();
       
    }//GEN-LAST:event_listAmigosMouseClicked
//eliminar amigo
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        grupoSeleccionado = cbGrupoActual.getSelectedItem().toString();
        amigoSeleccionado = listIntegrantes.getSelectedValue().toString();
      
        secuencialIndizado.ActualizarIndizado(SecuencialIndizado.GRUPOAMIGOS, FormatoDeData(usuario.getUser(), grupoSeleccionado, amigoSeleccionado) + "|0");
        integrantes.removeElement(amigoSeleccionado);
        listIntegrantes.setModel(integrantes);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbGrupoActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbGrupoActualMouseClicked
        // TODO add your handling code here:
        grupoSeleccionado = cbGrupoActual.getSelectedItem().toString();
        objGrupo = secuencial.LeerGrupo(secuencial.busqueda(false, usuario.getUser() + "|" + grupoSeleccionado, "c:\\MEIA\\BitácoraGrupos.txt", "c:\\MEIA\\Grupos.txt"));
        numeroDeIntegrantes = objGrupo.GetMiembros();
        tfNumeroIntegrantes.setText(Integer.toString(objGrupo.GetMiembros()));
        AmigosDelUsuario();
        
    }//GEN-LAST:event_cbGrupoActualMouseClicked

    private void cbGrupoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrupoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGrupoActualActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AmigosDelUsuario();
        this.tfNumeroIntegrantes.setText(Integer.toString(numeroDeIntegrantes));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AñadirIntegrante(){
        grupoSeleccionado = cbGrupoActual.getSelectedItem().toString();
        objGrupo = secuencial.LeerGrupo(secuencial.busqueda(false, usuario.getUser() + "|" + grupoSeleccionado, "c:\\MEIA\\BitácoraGrupos.txt", "c:\\MEIA\\Grupos.txt"));
        numeroDeIntegrantes = objGrupo.GetMiembros();
        amigoSeleccionado = listAmigos.getSelectedValue().toString();
        if (numeroDeIntegrantes == 0) {
            //ntegrantes.add(0, amigoSeleccionado);
            integrantes.addElement(amigoSeleccionado);
            numeroDeIntegrantes++;
        }else{
            //integrantes.add(numeroDeIntegrantes, HEIGHT);
            integrantes.addElement(amigoSeleccionado);
            numeroDeIntegrantes++;
          
        }
        
        
             //Actualizar el archivo de grupos
             //secuencial.Actualizar(usuario.getUser(), "ajdjfasd");
             
        listIntegrantes.setModel(integrantes);
        this.tfNumeroIntegrantes.setText(Integer.toString(numeroDeIntegrantes));

       
    }
    private void MostrarGrupos(){
        for (int i = 0; i < grupos.getSize(); i++) {
            cbGrupoActual.addItem((String)grupos.getElementAt(i));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupoAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupoAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupoAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupoAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupoAmigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGrupoActual;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listAmigos;
    private javax.swing.JList<String> listIntegrantes;
    private javax.swing.JTextField tfNumeroIntegrantes;
    private javax.swing.JTextField tfUsario;
    // End of variables declaration//GEN-END:variables
}
